name: Popcorn
options:
  createIntermediateGroups: true
configs:
  Debug: debug
  Release: release
configFiles:
  Debug: Configs/Debug.xcconfig
  Release: Configs/Release.xcconfig

settings:
  base:
    SWIFT_VERSION: 5.9

schemes:
  Popcorn:
    build:
      targets:
        Popcorn: all
        PopcornTests: [test]
    test:
      targets:
        - PopcornTests



targets:
  Popcorn:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Popcorn
    resources:
      - path: Popcorn/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.enzo.Popcorn
        INFOPLIST_FILE: Popcorn/Info.plist
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
  PopcornTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: PopcornTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.enzo.PopcornTests
        INFOPLIST_FILE: PopcornTests/Info.plist
    dependencies:
      - target: Popcorn
